language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - python setup.py install

script:
  - python setup.py test
  
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: release.sh release
          skip_cleanup: yes
          on:
            branch: master